image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake build-essential lcov curl mercurial cppcheck software-properties-common
          - gcc -v
          - g++ -v
          # Ignition dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease xenial main" > /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt-get update
          - apt-get -y install
            libignition-math5-dev
            libeigen3-dev
          # Use the branch of ign-cmake needed by ign-plugin WarningSuppression_CoreDirectory
          - hg clone https://bitbucket.org/ignitionrobotics/ign-cmake -b WarningSuppression_CoreDirectory
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - make
          - make install
          - cd ../..
          # Use ign-plugin
          - hg clone https://bitbucket.org/ignitionrobotics/ign-plugin -b NewRegistrationScheme
          - cd ign-plugin
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - make
          - make install
          - cd ../..
          # DARTsim
          - apt-add-repository -y ppa:dartsim
          - apt-get update
          - apt-get -y install
            dart6-data
            libdart6-dev
            libdart6-utils-urdf-dev
          # Ignition physics
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make
          - export CTEST_OUTPUT_ON_FAILURE=1
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make codecheck
          - make install
